version: "2"
services:
  web:
    build: .
    container_name: web_service
    ports:
      - 8000:80
    volumes:
      - ./html:/ver/www/html/
    depends_on:
      - db
  db:
    image: mysql:5.7.44
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234